<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Monitors (2)</name>
   <tag></tag>
   <elementGuidId>f0463bc0-95a3-4835-8df0-4490c2d5e664</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='menu']/div[2]/ul/li[3]/div/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9558fc43-6b2e-416e-8b03-0250632264ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://naveenautomationlabs.com/opencart/index.php?route=product/category&amp;path=25_28</value>
      <webElementGuid>10ad131d-1b31-4362-a604-1f7097b1678d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monitors (2)</value>
      <webElementGuid>a3d265e3-94be-484d-98db-c3f0d693f69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;collapse navbar-collapse navbar-ex1-collapse&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;dropdown&quot;]/div[@class=&quot;dropdown-menu&quot;]/div[@class=&quot;dropdown-inner&quot;]/ul[@class=&quot;list-unstyled&quot;]/li[2]/a[1]</value>
      <webElementGuid>1d9156a6-d555-40a9-8201-f9dbe0d5a083</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='menu']/div[2]/ul/li[3]/div/div/ul/li[2]/a</value>
      <webElementGuid>a6778927-d59f-489e-82b8-7b2e8ce321bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Monitors (2)')]</value>
      <webElementGuid>6806cf05-fb30-4670-b969-140c98e3dcc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mice and Trackballs (0)'])[1]/following::a[1]</value>
      <webElementGuid>efae80bd-fa24-439f-bfa0-8929865c7dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Components'])[1]/following::a[2]</value>
      <webElementGuid>cc3c71b2-db3b-45c1-9402-163c1d2472cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Printers (0)'])[1]/preceding::a[1]</value>
      <webElementGuid>ed181b0e-20a2-4178-83e6-964dae1dbf2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scanners (0)'])[1]/preceding::a[2]</value>
      <webElementGuid>5f996b7e-bfe6-45ce-97c2-82cac53f93ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Monitors (2)']/parent::*</value>
      <webElementGuid>99806b97-fc31-4169-a0c9-26e000eead50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://naveenautomationlabs.com/opencart/index.php?route=product/category&amp;path=25_28')]</value>
      <webElementGuid>f70695b7-07ae-4b3a-a26a-b435b983c68e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/ul/li[2]/a</value>
      <webElementGuid>c811c78f-196b-41e0-b460-8c6cdce5967c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://naveenautomationlabs.com/opencart/index.php?route=product/category&amp;path=25_28' and (text() = 'Monitors (2)' or . = 'Monitors (2)')]</value>
      <webElementGuid>e58093f2-4b33-4abd-8e95-73a473fe6b28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
